# Generated by Django 5.2.3 on 2025-06-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_new',
            name='contact',
        ),
    ]
