# Generated by Django 5.2.3 on 2025-06-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_new_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_new',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
