# Generated by Django 5.1.7 on 2025-06-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendationsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('Question', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Answer', models.TextField()),
            ],
        ),
    ]
